const BUILTIN = 'builtin';
const ES5 = 'es5';
const ES2015 = 'es2015';
const ES2016 = 'es2016';
const ES2017 = 'es2017';
const ES2018 = 'es2018';

const amdGlobals = {
	define: { canOverride: false },
	require: { canOverride: false },
};

const browserGlobals = {
	AbortController: { canOverride: false },
	AbortSignal: { canOverride: false },
	addEventListener: { canOverride: false },
	alert: { canOverride: false },
	AnalyserNode: { canOverride: false },
	Animation: { canOverride: false },
	AnimationEffectReadOnly: { canOverride: false },
	AnimationEffectTiming: { canOverride: false },
	AnimationEffectTimingReadOnly: { canOverride: false },
	AnimationEvent: { canOverride: false },
	AnimationPlaybackEvent: { canOverride: false },
	AnimationTimeline: { canOverride: false },
	applicationCache: { canOverride: false },
	ApplicationCache: { canOverride: false },
	ApplicationCacheErrorEvent: { canOverride: false },
	atob: { canOverride: false },
	Attr: { canOverride: false },
	Audio: { canOverride: false },
	AudioBuffer: { canOverride: false },
	AudioBufferSourceNode: { canOverride: false },
	AudioContext: { canOverride: false },
	AudioDestinationNode: { canOverride: false },
	AudioListener: { canOverride: false },
	AudioNode: { canOverride: false },
	AudioParam: { canOverride: false },
	AudioProcessingEvent: { canOverride: false },
	AudioScheduledSourceNode: { canOverride: false },
	BarProp: { canOverride: false },
	BaseAudioContext: { canOverride: false },
	BatteryManager: { canOverride: false },
	BeforeUnloadEvent: { canOverride: false },
	BiquadFilterNode: { canOverride: false },
	Blob: { canOverride: false },
	BlobEvent: { canOverride: false },
	blur: { canOverride: false },
	BroadcastChannel: { canOverride: false },
	btoa: { canOverride: false },
	BudgetService: { canOverride: false },
	ByteLengthQueuingStrategy: { canOverride: false },
	Cache: { canOverride: false },
	caches: { canOverride: false },
	CacheStorage: { canOverride: false },
	cancelAnimationFrame: { canOverride: false },
	cancelIdleCallback: { canOverride: false },
	CanvasCaptureMediaStreamTrack: { canOverride: false },
	CanvasGradient: { canOverride: false },
	CanvasPattern: { canOverride: false },
	CanvasRenderingContext2D: { canOverride: false },
	ChannelMergerNode: { canOverride: false },
	ChannelSplitterNode: { canOverride: false },
	CharacterData: { canOverride: false },
	clearInterval: { canOverride: false },
	clearTimeout: { canOverride: false },
	clientInformation: { canOverride: false },
	ClipboardEvent: { canOverride: false },
	close: { canOverride: false },
	closed: { canOverride: false },
	CloseEvent: { canOverride: false },
	Comment: { canOverride: false },
	CompositionEvent: { canOverride: false },
	confirm: { canOverride: false },
	console: { canOverride: false },
	ConstantSourceNode: { canOverride: false },
	ConvolverNode: { canOverride: false },
	CountQueuingStrategy: { canOverride: false },
	createImageBitmap: { canOverride: false },
	Credential: { canOverride: false },
	CredentialsContainer: { canOverride: false },
	crypto: { canOverride: false },
	Crypto: { canOverride: false },
	CryptoKey: { canOverride: false },
	CSS: { canOverride: false },
	CSSConditionRule: { canOverride: false },
	CSSFontFaceRule: { canOverride: false },
	CSSGroupingRule: { canOverride: false },
	CSSImportRule: { canOverride: false },
	CSSKeyframeRule: { canOverride: false },
	CSSKeyframesRule: { canOverride: false },
	CSSMediaRule: { canOverride: false },
	CSSNamespaceRule: { canOverride: false },
	CSSPageRule: { canOverride: false },
	CSSRule: { canOverride: false },
	CSSRuleList: { canOverride: false },
	CSSStyleDeclaration: { canOverride: false },
	CSSStyleRule: { canOverride: false },
	CSSStyleSheet: { canOverride: false },
	CSSSupportsRule: { canOverride: false },
	CustomElementRegistry: { canOverride: false },
	customElements: { canOverride: false },
	CustomEvent: { canOverride: false },
	DataTransfer: { canOverride: false },
	DataTransferItem: { canOverride: false },
	DataTransferItemList: { canOverride: false },
	defaultstatus: { canOverride: false },
	defaultStatus: { canOverride: false },
	DelayNode: { canOverride: false },
	DeviceMotionEvent: { canOverride: false },
	DeviceOrientationEvent: { canOverride: false },
	devicePixelRatio: { canOverride: false },
	dispatchEvent: { canOverride: false },
	document: { canOverride: false },
	Document: { canOverride: false },
	DocumentFragment: { canOverride: false },
	DocumentType: { canOverride: false },
	DOMError: { canOverride: false },
	DOMException: { canOverride: false },
	DOMImplementation: { canOverride: false },
	DOMMatrix: { canOverride: false },
	DOMMatrixReadOnly: { canOverride: false },
	DOMParser: { canOverride: false },
	DOMPoint: { canOverride: false },
	DOMPointReadOnly: { canOverride: false },
	DOMQuad: { canOverride: false },
	DOMRect: { canOverride: false },
	DOMRectReadOnly: { canOverride: false },
	DOMStringList: { canOverride: false },
	DOMStringMap: { canOverride: false },
	DOMTokenList: { canOverride: false },
	DragEvent: { canOverride: false },
	DynamicsCompressorNode: { canOverride: false },
	Element: { canOverride: false },
	ErrorEvent: { canOverride: false },
	event: { canOverride: false },
	Event: { canOverride: false },
	EventSource: { canOverride: false },
	EventTarget: { canOverride: false },
	external: { canOverride: false },
	fetch: { canOverride: false },
	File: { canOverride: false },
	FileList: { canOverride: false },
	FileReader: { canOverride: false },
	find: { canOverride: false },
	focus: { canOverride: false },
	FocusEvent: { canOverride: false },
	FontFace: { canOverride: false },
	FontFaceSetLoadEvent: { canOverride: false },
	FormData: { canOverride: false },
	frameElement: { canOverride: false },
	frames: { canOverride: false },
	GainNode: { canOverride: false },
	Gamepad: { canOverride: false },
	GamepadButton: { canOverride: false },
	GamepadEvent: { canOverride: false },
	getComputedStyle: { canOverride: false },
	getSelection: { canOverride: false },
	HashChangeEvent: { canOverride: false },
	Headers: { canOverride: false },
	history: { canOverride: false },
	History: { canOverride: false },
	HTMLAllCollection: { canOverride: false },
	HTMLAnchorElement: { canOverride: false },
	HTMLAreaElement: { canOverride: false },
	HTMLAudioElement: { canOverride: false },
	HTMLBaseElement: { canOverride: false },
	HTMLBodyElement: { canOverride: false },
	HTMLBRElement: { canOverride: false },
	HTMLButtonElement: { canOverride: false },
	HTMLCanvasElement: { canOverride: false },
	HTMLCollection: { canOverride: false },
	HTMLContentElement: { canOverride: false },
	HTMLDataElement: { canOverride: false },
	HTMLDataListElement: { canOverride: false },
	HTMLDetailsElement: { canOverride: false },
	HTMLDialogElement: { canOverride: false },
	HTMLDirectoryElement: { canOverride: false },
	HTMLDivElement: { canOverride: false },
	HTMLDListElement: { canOverride: false },
	HTMLDocument: { canOverride: false },
	HTMLElement: { canOverride: false },
	HTMLEmbedElement: { canOverride: false },
	HTMLFieldSetElement: { canOverride: false },
	HTMLFontElement: { canOverride: false },
	HTMLFormControlsCollection: { canOverride: false },
	HTMLFormElement: { canOverride: false },
	HTMLFrameElement: { canOverride: false },
	HTMLFrameSetElement: { canOverride: false },
	HTMLHeadElement: { canOverride: false },
	HTMLHeadingElement: { canOverride: false },
	HTMLHRElement: { canOverride: false },
	HTMLHtmlElement: { canOverride: false },
	HTMLIFrameElement: { canOverride: false },
	HTMLImageElement: { canOverride: false },
	HTMLInputElement: { canOverride: false },
	HTMLLabelElement: { canOverride: false },
	HTMLLegendElement: { canOverride: false },
	HTMLLIElement: { canOverride: false },
	HTMLLinkElement: { canOverride: false },
	HTMLMapElement: { canOverride: false },
	HTMLMarqueeElement: { canOverride: false },
	HTMLMediaElement: { canOverride: false },
	HTMLMenuElement: { canOverride: false },
	HTMLMetaElement: { canOverride: false },
	HTMLMeterElement: { canOverride: false },
	HTMLModElement: { canOverride: false },
	HTMLObjectElement: { canOverride: false },
	HTMLOListElement: { canOverride: false },
	HTMLOptGroupElement: { canOverride: false },
	HTMLOptionElement: { canOverride: false },
	HTMLOptionsCollection: { canOverride: false },
	HTMLOutputElement: { canOverride: false },
	HTMLParagraphElement: { canOverride: false },
	HTMLParamElement: { canOverride: false },
	HTMLPictureElement: { canOverride: false },
	HTMLPreElement: { canOverride: false },
	HTMLProgressElement: { canOverride: false },
	HTMLQuoteElement: { canOverride: false },
	HTMLScriptElement: { canOverride: false },
	HTMLSelectElement: { canOverride: false },
	HTMLShadowElement: { canOverride: false },
	HTMLSlotElement: { canOverride: false },
	HTMLSourceElement: { canOverride: false },
	HTMLSpanElement: { canOverride: false },
	HTMLStyleElement: { canOverride: false },
	HTMLTableCaptionElement: { canOverride: false },
	HTMLTableCellElement: { canOverride: false },
	HTMLTableColElement: { canOverride: false },
	HTMLTableElement: { canOverride: false },
	HTMLTableRowElement: { canOverride: false },
	HTMLTableSectionElement: { canOverride: false },
	HTMLTemplateElement: { canOverride: false },
	HTMLTextAreaElement: { canOverride: false },
	HTMLTimeElement: { canOverride: false },
	HTMLTitleElement: { canOverride: false },
	HTMLTrackElement: { canOverride: false },
	HTMLUListElement: { canOverride: false },
	HTMLUnknownElement: { canOverride: false },
	HTMLVideoElement: { canOverride: false },
	IDBCursor: { canOverride: false },
	IDBCursorWithValue: { canOverride: false },
	IDBDatabase: { canOverride: false },
	IDBFactory: { canOverride: false },
	IDBIndex: { canOverride: false },
	IDBKeyRange: { canOverride: false },
	IDBObjectStore: { canOverride: false },
	IDBOpenDBRequest: { canOverride: false },
	IDBRequest: { canOverride: false },
	IDBTransaction: { canOverride: false },
	IDBVersionChangeEvent: { canOverride: false },
	IdleDeadline: { canOverride: false },
	IIRFilterNode: { canOverride: false },
	Image: { canOverride: false },
	ImageBitmap: { canOverride: false },
	ImageBitmapRenderingContext: { canOverride: false },
	ImageCapture: { canOverride: false },
	ImageData: { canOverride: false },
	indexedDB: { canOverride: false },
	innerHeight: { canOverride: false },
	innerWidth: { canOverride: false },
	InputEvent: { canOverride: false },
	IntersectionObserver: { canOverride: false },
	IntersectionObserverEntry: { canOverride: false },
	Intl: { canOverride: false },
	isSecureContext: { canOverride: false },
	KeyboardEvent: { canOverride: false },
	KeyframeEffect: { canOverride: false },
	KeyframeEffectReadOnly: { canOverride: false },
	length: { canOverride: false },
	localStorage: { canOverride: false },
	location: { canOverride: false },
	Location: { canOverride: false },
	locationbar: { canOverride: false },
	matchMedia: { canOverride: false },
	MediaDeviceInfo: { canOverride: false },
	MediaDevices: { canOverride: false },
	MediaElementAudioSourceNode: { canOverride: false },
	MediaEncryptedEvent: { canOverride: false },
	MediaError: { canOverride: false },
	MediaKeyMessageEvent: { canOverride: false },
	MediaKeySession: { canOverride: false },
	MediaKeyStatusMap: { canOverride: false },
	MediaKeySystemAccess: { canOverride: false },
	MediaList: { canOverride: false },
	MediaQueryList: { canOverride: false },
	MediaQueryListEvent: { canOverride: false },
	MediaRecorder: { canOverride: false },
	MediaSettingsRange: { canOverride: false },
	MediaSource: { canOverride: false },
	MediaStream: { canOverride: false },
	MediaStreamAudioDestinationNode: { canOverride: false },
	MediaStreamAudioSourceNode: { canOverride: false },
	MediaStreamEvent: { canOverride: false },
	MediaStreamTrack: { canOverride: false },
	MediaStreamTrackEvent: { canOverride: false },
	menubar: { canOverride: false },
	MessageChannel: { canOverride: false },
	MessageEvent: { canOverride: false },
	MessagePort: { canOverride: false },
	MIDIAccess: { canOverride: false },
	MIDIConnectionEvent: { canOverride: false },
	MIDIInput: { canOverride: false },
	MIDIInputMap: { canOverride: false },
	MIDIMessageEvent: { canOverride: false },
	MIDIOutput: { canOverride: false },
	MIDIOutputMap: { canOverride: false },
	MIDIPort: { canOverride: false },
	MimeType: { canOverride: false },
	MimeTypeArray: { canOverride: false },
	MouseEvent: { canOverride: false },
	moveBy: { canOverride: false },
	moveTo: { canOverride: false },
	MutationEvent: { canOverride: false },
	MutationObserver: { canOverride: false },
	MutationRecord: { canOverride: false },
	name: { canOverride: false },
	NamedNodeMap: { canOverride: false },
	NavigationPreloadManager: { canOverride: false },
	navigator: { canOverride: false },
	Navigator: { canOverride: false },
	NetworkInformation: { canOverride: false },
	Node: { canOverride: false },
	NodeFilter: { canOverride: false },
	NodeIterator: { canOverride: false },
	NodeList: { canOverride: false },
	Notification: { canOverride: false },
	OfflineAudioCompletionEvent: { canOverride: false },
	OfflineAudioContext: { canOverride: false },
	offscreenBuffering: { canOverride: false },
	OffscreenCanvas: { canOverride: true },
	onabort: { canOverride: true },
	onafterprint: { canOverride: true },
	onanimationend: { canOverride: true },
	onanimationiteration: { canOverride: true },
	onanimationstart: { canOverride: true },
	onappinstalled: { canOverride: true },
	onauxclick: { canOverride: true },
	onbeforeinstallprompt: { canOverride: true },
	onbeforeprint: { canOverride: true },
	onbeforeunload: { canOverride: true },
	onblur: { canOverride: true },
	oncancel: { canOverride: true },
	oncanplay: { canOverride: true },
	oncanplaythrough: { canOverride: true },
	onchange: { canOverride: true },
	onclick: { canOverride: true },
	onclose: { canOverride: true },
	oncontextmenu: { canOverride: true },
	oncuechange: { canOverride: true },
	ondblclick: { canOverride: true },
	ondevicemotion: { canOverride: true },
	ondeviceorientation: { canOverride: true },
	ondeviceorientationabsolute: { canOverride: true },
	ondrag: { canOverride: true },
	ondragend: { canOverride: true },
	ondragenter: { canOverride: true },
	ondragleave: { canOverride: true },
	ondragover: { canOverride: true },
	ondragstart: { canOverride: true },
	ondrop: { canOverride: true },
	ondurationchange: { canOverride: true },
	onemptied: { canOverride: true },
	onended: { canOverride: true },
	onerror: { canOverride: true },
	onfocus: { canOverride: true },
	ongotpointercapture: { canOverride: true },
	onhashchange: { canOverride: true },
	oninput: { canOverride: true },
	oninvalid: { canOverride: true },
	onkeydown: { canOverride: true },
	onkeypress: { canOverride: true },
	onkeyup: { canOverride: true },
	onlanguagechange: { canOverride: true },
	onload: { canOverride: true },
	onloadeddata: { canOverride: true },
	onloadedmetadata: { canOverride: true },
	onloadstart: { canOverride: true },
	onlostpointercapture: { canOverride: true },
	onmessage: { canOverride: true },
	onmessageerror: { canOverride: true },
	onmousedown: { canOverride: true },
	onmouseenter: { canOverride: true },
	onmouseleave: { canOverride: true },
	onmousemove: { canOverride: true },
	onmouseout: { canOverride: true },
	onmouseover: { canOverride: true },
	onmouseup: { canOverride: true },
	onmousewheel: { canOverride: true },
	onoffline: { canOverride: true },
	ononline: { canOverride: true },
	onpagehide: { canOverride: true },
	onpageshow: { canOverride: true },
	onpause: { canOverride: true },
	onplay: { canOverride: true },
	onplaying: { canOverride: true },
	onpointercancel: { canOverride: true },
	onpointerdown: { canOverride: true },
	onpointerenter: { canOverride: true },
	onpointerleave: { canOverride: true },
	onpointermove: { canOverride: true },
	onpointerout: { canOverride: true },
	onpointerover: { canOverride: true },
	onpointerup: { canOverride: true },
	onpopstate: { canOverride: true },
	onprogress: { canOverride: true },
	onratechange: { canOverride: true },
	onrejectionhandled: { canOverride: true },
	onreset: { canOverride: true },
	onresize: { canOverride: true },
	onscroll: { canOverride: true },
	onsearch: { canOverride: true },
	onseeked: { canOverride: true },
	onseeking: { canOverride: true },
	onselect: { canOverride: true },
	onstalled: { canOverride: true },
	onstorage: { canOverride: true },
	onsubmit: { canOverride: true },
	onsuspend: { canOverride: true },
	ontimeupdate: { canOverride: true },
	ontoggle: { canOverride: true },
	ontransitionend: { canOverride: true },
	onunhandledrejection: { canOverride: true },
	onunload: { canOverride: true },
	onvolumechange: { canOverride: true },
	onwaiting: { canOverride: true },
	onwheel: { canOverride: true },
	open: { canOverride: false },
	openDatabase: { canOverride: false },
	opener: { canOverride: false },
	Option: { canOverride: false },
	origin: { canOverride: false },
	OscillatorNode: { canOverride: false },
	outerHeight: { canOverride: false },
	outerWidth: { canOverride: false },
	PageTransitionEvent: { canOverride: false },
	pageXOffset: { canOverride: false },
	pageYOffset: { canOverride: false },
	PannerNode: { canOverride: false },
	parent: { canOverride: false },
	Path2D: { canOverride: false },
	PaymentAddress: { canOverride: false },
	PaymentRequest: { canOverride: false },
	PaymentRequestUpdateEvent: { canOverride: false },
	PaymentResponse: { canOverride: false },
	performance: { canOverride: false },
	Performance: { canOverride: false },
	PerformanceEntry: { canOverride: false },
	PerformanceLongTaskTiming: { canOverride: false },
	PerformanceMark: { canOverride: false },
	PerformanceMeasure: { canOverride: false },
	PerformanceNavigation: { canOverride: false },
	PerformanceNavigationTiming: { canOverride: false },
	PerformanceObserver: { canOverride: false },
	PerformanceObserverEntryList: { canOverride: false },
	PerformancePaintTiming: { canOverride: false },
	PerformanceResourceTiming: { canOverride: false },
	PerformanceTiming: { canOverride: false },
	PeriodicWave: { canOverride: false },
	Permissions: { canOverride: false },
	PermissionStatus: { canOverride: false },
	personalbar: { canOverride: false },
	PhotoCapabilities: { canOverride: false },
	Plugin: { canOverride: false },
	PluginArray: { canOverride: false },
	PointerEvent: { canOverride: false },
	PopStateEvent: { canOverride: false },
	postMessage: { canOverride: false },
	Presentation: { canOverride: false },
	PresentationAvailability: { canOverride: false },
	PresentationConnection: { canOverride: false },
	PresentationConnectionAvailableEvent: { canOverride: false },
	PresentationConnectionCloseEvent: { canOverride: false },
	PresentationConnectionList: { canOverride: false },
	PresentationReceiver: { canOverride: false },
	PresentationRequest: { canOverride: false },
	print: { canOverride: false },
	ProcessingInstruction: { canOverride: false },
	ProgressEvent: { canOverride: false },
	PromiseRejectionEvent: { canOverride: false },
	prompt: { canOverride: false },
	PushManager: { canOverride: false },
	PushSubscription: { canOverride: false },
	PushSubscriptionOptions: { canOverride: false },
	RadioNodeList: { canOverride: false },
	Range: { canOverride: false },
	ReadableStream: { canOverride: false },
	RemotePlayback: { canOverride: false },
	removeEventListener: { canOverride: false },
	Request: { canOverride: false },
	requestAnimationFrame: { canOverride: false },
	requestIdleCallback: { canOverride: false },
	resizeBy: { canOverride: false },
	ResizeObserver: { canOverride: false },
	ResizeObserverEntry: { canOverride: false },
	resizeTo: { canOverride: false },
	Response: { canOverride: false },
	RTCCertificate: { canOverride: false },
	RTCDataChannel: { canOverride: false },
	RTCDataChannelEvent: { canOverride: false },
	RTCDtlsTransport: { canOverride: false },
	RTCIceCandidate: { canOverride: false },
	RTCIceGatherer: { canOverride: false },
	RTCIceTransport: { canOverride: false },
	RTCPeerConnection: { canOverride: false },
	RTCPeerConnectionIceEvent: { canOverride: false },
	RTCRtpContributingSource: { canOverride: false },
	RTCRtpReceiver: { canOverride: false },
	RTCRtpSender: { canOverride: false },
	RTCSctpTransport: { canOverride: false },
	RTCSessionDescription: { canOverride: false },
	RTCStatsReport: { canOverride: false },
	RTCTrackEvent: { canOverride: false },
	screen: { canOverride: false },
	Screen: { canOverride: false },
	screenLeft: { canOverride: false },
	ScreenOrientation: { canOverride: false },
	screenTop: { canOverride: false },
	screenX: { canOverride: false },
	screenY: { canOverride: false },
	ScriptProcessorNode: { canOverride: false },
	scroll: { canOverride: false },
	scrollbars: { canOverride: false },
	scrollBy: { canOverride: false },
	scrollTo: { canOverride: false },
	scrollX: { canOverride: false },
	scrollY: { canOverride: false },
	SecurityPolicyViolationEvent: { canOverride: false },
	Selection: { canOverride: false },
	self: { canOverride: false },
	ServiceWorker: { canOverride: false },
	ServiceWorkerContainer: { canOverride: false },
	ServiceWorkerRegistration: { canOverride: false },
	sessionStorage: { canOverride: false },
	setInterval: { canOverride: false },
	setTimeout: { canOverride: false },
	ShadowRoot: { canOverride: false },
	SharedWorker: { canOverride: false },
	SourceBuffer: { canOverride: false },
	SourceBufferList: { canOverride: false },
	speechSynthesis: { canOverride: false },
	SpeechSynthesisEvent: { canOverride: false },
	SpeechSynthesisUtterance: { canOverride: false },
	StaticRange: { canOverride: false },
	status: { canOverride: false },
	statusbar: { canOverride: false },
	StereoPannerNode: { canOverride: false },
	stop: { canOverride: false },
	Storage: { canOverride: false },
	StorageEvent: { canOverride: false },
	StorageManager: { canOverride: false },
	styleMedia: { canOverride: false },
	StyleSheet: { canOverride: false },
	StyleSheetList: { canOverride: false },
	SubtleCrypto: { canOverride: false },
	SVGAElement: { canOverride: false },
	SVGAngle: { canOverride: false },
	SVGAnimatedAngle: { canOverride: false },
	SVGAnimatedBoolean: { canOverride: false },
	SVGAnimatedEnumeration: { canOverride: false },
	SVGAnimatedInteger: { canOverride: false },
	SVGAnimatedLength: { canOverride: false },
	SVGAnimatedLengthList: { canOverride: false },
	SVGAnimatedNumber: { canOverride: false },
	SVGAnimatedNumberList: { canOverride: false },
	SVGAnimatedPreserveAspectRatio: { canOverride: false },
	SVGAnimatedRect: { canOverride: false },
	SVGAnimatedString: { canOverride: false },
	SVGAnimatedTransformList: { canOverride: false },
	SVGAnimateElement: { canOverride: false },
	SVGAnimateMotionElement: { canOverride: false },
	SVGAnimateTransformElement: { canOverride: false },
	SVGAnimationElement: { canOverride: false },
	SVGCircleElement: { canOverride: false },
	SVGClipPathElement: { canOverride: false },
	SVGComponentTransferFunctionElement: { canOverride: false },
	SVGDefsElement: { canOverride: false },
	SVGDescElement: { canOverride: false },
	SVGDiscardElement: { canOverride: false },
	SVGElement: { canOverride: false },
	SVGEllipseElement: { canOverride: false },
	SVGFEBlendElement: { canOverride: false },
	SVGFEColorMatrixElement: { canOverride: false },
	SVGFEComponentTransferElement: { canOverride: false },
	SVGFECompositeElement: { canOverride: false },
	SVGFEConvolveMatrixElement: { canOverride: false },
	SVGFEDiffuseLightingElement: { canOverride: false },
	SVGFEDisplacementMapElement: { canOverride: false },
	SVGFEDistantLightElement: { canOverride: false },
	SVGFEDropShadowElement: { canOverride: false },
	SVGFEFloodElement: { canOverride: false },
	SVGFEFuncAElement: { canOverride: false },
	SVGFEFuncBElement: { canOverride: false },
	SVGFEFuncGElement: { canOverride: false },
	SVGFEFuncRElement: { canOverride: false },
	SVGFEGaussianBlurElement: { canOverride: false },
	SVGFEImageElement: { canOverride: false },
	SVGFEMergeElement: { canOverride: false },
	SVGFEMergeNodeElement: { canOverride: false },
	SVGFEMorphologyElement: { canOverride: false },
	SVGFEOffsetElement: { canOverride: false },
	SVGFEPointLightElement: { canOverride: false },
	SVGFESpecularLightingElement: { canOverride: false },
	SVGFESpotLightElement: { canOverride: false },
	SVGFETileElement: { canOverride: false },
	SVGFETurbulenceElement: { canOverride: false },
	SVGFilterElement: { canOverride: false },
	SVGForeignObjectElement: { canOverride: false },
	SVGGElement: { canOverride: false },
	SVGGeometryElement: { canOverride: false },
	SVGGradientElement: { canOverride: false },
	SVGGraphicsElement: { canOverride: false },
	SVGImageElement: { canOverride: false },
	SVGLength: { canOverride: false },
	SVGLengthList: { canOverride: false },
	SVGLinearGradientElement: { canOverride: false },
	SVGLineElement: { canOverride: false },
	SVGMarkerElement: { canOverride: false },
	SVGMaskElement: { canOverride: false },
	SVGMatrix: { canOverride: false },
	SVGMetadataElement: { canOverride: false },
	SVGMPathElement: { canOverride: false },
	SVGNumber: { canOverride: false },
	SVGNumberList: { canOverride: false },
	SVGPathElement: { canOverride: false },
	SVGPatternElement: { canOverride: false },
	SVGPoint: { canOverride: false },
	SVGPointList: { canOverride: false },
	SVGPolygonElement: { canOverride: false },
	SVGPolylineElement: { canOverride: false },
	SVGPreserveAspectRatio: { canOverride: false },
	SVGRadialGradientElement: { canOverride: false },
	SVGRect: { canOverride: false },
	SVGRectElement: { canOverride: false },
	SVGScriptElement: { canOverride: false },
	SVGSetElement: { canOverride: false },
	SVGStopElement: { canOverride: false },
	SVGStringList: { canOverride: false },
	SVGStyleElement: { canOverride: false },
	SVGSVGElement: { canOverride: false },
	SVGSwitchElement: { canOverride: false },
	SVGSymbolElement: { canOverride: false },
	SVGTextContentElement: { canOverride: false },
	SVGTextElement: { canOverride: false },
	SVGTextPathElement: { canOverride: false },
	SVGTextPositioningElement: { canOverride: false },
	SVGTitleElement: { canOverride: false },
	SVGTransform: { canOverride: false },
	SVGTransformList: { canOverride: false },
	SVGTSpanElement: { canOverride: false },
	SVGUnitTypes: { canOverride: false },
	SVGUseElement: { canOverride: false },
	SVGViewElement: { canOverride: false },
	TaskAttributionTiming: { canOverride: false },
	Text: { canOverride: false },
	TextDecoder: { canOverride: false },
	TextEncoder: { canOverride: false },
	TextEvent: { canOverride: false },
	TextMetrics: { canOverride: false },
	TextTrack: { canOverride: false },
	TextTrackCue: { canOverride: false },
	TextTrackCueList: { canOverride: false },
	TextTrackList: { canOverride: false },
	TimeRanges: { canOverride: false },
	toolbar: { canOverride: false },
	top: { canOverride: false },
	Touch: { canOverride: false },
	TouchEvent: { canOverride: false },
	TouchList: { canOverride: false },
	TrackEvent: { canOverride: false },
	TransitionEvent: { canOverride: false },
	TreeWalker: { canOverride: false },
	UIEvent: { canOverride: false },
	URL: { canOverride: false },
	URLSearchParams: { canOverride: false },
	ValidityState: { canOverride: false },
	visualViewport: { canOverride: false },
	VisualViewport: { canOverride: false },
	VTTCue: { canOverride: false },
	WaveShaperNode: { canOverride: false },
	WebAssembly: { canOverride: false },
	WebGL2RenderingContext: { canOverride: false },
	WebGLActiveInfo: { canOverride: false },
	WebGLBuffer: { canOverride: false },
	WebGLContextEvent: { canOverride: false },
	WebGLFramebuffer: { canOverride: false },
	WebGLProgram: { canOverride: false },
	WebGLQuery: { canOverride: false },
	WebGLRenderbuffer: { canOverride: false },
	WebGLRenderingContext: { canOverride: false },
	WebGLSampler: { canOverride: false },
	WebGLShader: { canOverride: false },
	WebGLShaderPrecisionFormat: { canOverride: false },
	WebGLSync: { canOverride: false },
	WebGLTexture: { canOverride: false },
	WebGLTransformFeedback: { canOverride: false },
	WebGLUniformLocation: { canOverride: false },
	WebGLVertexArrayObject: { canOverride: false },
	WebSocket: { canOverride: false },
	WheelEvent: { canOverride: false },
	window: { canOverride: false },
	Window: { canOverride: false },
	Worker: { canOverride: false },
	WritableStream: { canOverride: false },
	XMLDocument: { canOverride: false },
	XMLHttpRequest: { canOverride: false },
	XMLHttpRequestEventTarget: { canOverride: false },
	XMLHttpRequestUpload: { canOverride: false },
	XMLSerializer: { canOverride: false },
	XPathEvaluator: { canOverride: false },
	XPathExpression: { canOverride: false },
	XPathResult: { canOverride: false },
	XSLTProcessor: { canOverride: false },
};

const commonjsGlobals = {
	exports: { canOverride: true },
	global: { canOverride: false },
	module: { canOverride: false },
	require: { canOverride: false },
};

const esXXXXGlobals = {
	Array:              	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	ArrayBuffer:        	{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Atomics:            	{ canOverride: false, in: [BUILTIN, ES2017] },
	Boolean:            	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	"constructor":      	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	DataView:           	{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Date:               	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	decodeURI:          	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	decodeURIComponent: 	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	encodeURI:          	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	encodeURIComponent: 	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Error:              	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	escape:             	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	eval:               	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	EvalError:          	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Float32Array:       	{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Float64Array:       	{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Function:           	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	hasOwnProperty:     	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Infinity:           	{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Int8Array:          	{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Int16Array: 					{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Int32Array: 					{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	isFinite: 						{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	isNaN: 								{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	isPrototypeOf: 				{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	JSON: 								{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Map: 									{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Math: 								{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	NaN: 									{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Number: 							{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Object: 							{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	parseFloat: 					{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	parseInt: 						{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Promise: 							{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	propertyIsEnumerable: { canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Proxy: 								{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	RangeError: 					{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	ReferenceError: 			{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Reflect: 							{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	RegExp: 							{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Set: 									{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	SharedArrayBuffer: 		{ canOverride: false, in: [BUILTIN, ES2017] },
	String: 							{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Symbol: 							{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	SyntaxError: 					{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	toLocalString: 				{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	toString: 						{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	TypeError: 						{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	Uint8Array: 					{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Uint8ClampedArray: 		{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Uint16Array: 					{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	Uint32Array: 					{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	undefined: 						{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	unescape: 						{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	URIError: 						{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	valueOf: 							{ canOverride: false, in: [BUILTIN, ES5, ES2015, ES2017] },
	WeakMap: 							{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
	WeakSet: 							{ canOverride: false, in: [BUILTIN, ES2015, ES2017] },
};

const nodeGlobals = {
	__dirname: { canOverride: false },
	__filename: { canOverride: false },
	Buffer: { canOverride: false },
	clearImmediate: { canOverride: false },
	clearInterval: { canOverride: false },
	clearTimeout: { canOverride: false },
	console: { canOverride: false },
	exports: { canOverride: true },
	global: { canOverride: false },
	Intl: { canOverride: false },
	module: { canOverride: false },
	process: { canOverride: false },
	require: { canOverride: false },
	setImmediate: { canOverride: false },
	setInterval: { canOverride: false },
	setTimeout: { canOverride: false },
};

const serviceworkerGlobals = {
	Cache: { canOverride: false },
	caches: { canOverride: false },
	CacheStorage: { canOverride: false },
	Client: { canOverride: false },
	clients: { canOverride: false },
	Clients: { canOverride: false },
	ExtendableEvent: { canOverride: false },
	ExtendableMessageEvent: { canOverride: false },
	FetchEvent: { canOverride: false },
	importScripts: { canOverride: false },
	registration: { canOverride: false },
	self: { canOverride: false },
	ServiceWorker: { canOverride: false },
	ServiceWorkerContainer: { canOverride: false },
	ServiceWorkerGlobalScope: { canOverride: false },
	ServiceWorkerMessageEvent: { canOverride: false },
	ServiceWorkerRegistration: { canOverride: false },
	skipWaiting: { canOverride: false },
	WindowClient: { canOverride: false },
};

const webextensionsGlobals = {
	browser: { canOverride: false },
	chrome: { canOverride: false },
	opr: { canOverride: false },
}

const workerGlobals = {
	applicationCache: { canOverride: false },
	atob: { canOverride: false },
	Blob: { canOverride: false },
	BroadcastChannel: { canOverride: false },
	btoa: { canOverride: false },
	Cache: { canOverride: false },
	caches: { canOverride: false },
	clearInterval: { canOverride: false },
	clearTimeout: { canOverride: false },
	close: { canOverride: true },
	console: { canOverride: false },
	fetch: { canOverride: false },
	FileReaderSync: { canOverride: false },
	FormData: { canOverride: false },
	Headers: { canOverride: false },
	IDBCursor: { canOverride: false },
	IDBCursorWithValue: { canOverride: false },
	IDBDatabase: { canOverride: false },
	IDBFactory: { canOverride: false },
	IDBIndex: { canOverride: false },
	IDBKeyRange: { canOverride: false },
	IDBObjectStore: { canOverride: false },
	IDBOpenDBRequest: { canOverride: false },
	IDBRequest: { canOverride: false },
	IDBTransaction: { canOverride: false },
	IDBVersionChangeEvent: { canOverride: false },
	ImageData: { canOverride: false },
	importScripts: { canOverride: true },
	indexedDB: { canOverride: false },
	location: { canOverride: false },
	MessageChannel: { canOverride: false },
	MessagePort: { canOverride: false },
	name: { canOverride: false },
	navigator: { canOverride: false },
	Notification: { canOverride: false },
	onclose: { canOverride: true },
	onconnect: { canOverride: true },
	onerror: { canOverride: true },
	onlanguagechange: { canOverride: true },
	onmessage: { canOverride: true },
	onoffline: { canOverride: true },
	ononline: { canOverride: true },
	onrejectionhandled: { canOverride: true },
	onunhandledrejection: { canOverride: true },
	performance: { canOverride: false },
	Performance: { canOverride: false },
	PerformanceEntry: { canOverride: false },
	PerformanceMark: { canOverride: false },
	PerformanceMeasure: { canOverride: false },
	PerformanceNavigation: { canOverride: false },
	PerformanceResourceTiming: { canOverride: false },
	PerformanceTiming: { canOverride: false },
	postMessage: { canOverride: true },
	Promise: { canOverride: false },
	Request: { canOverride: false },
	Response: { canOverride: false },
	self: { canOverride: true },
	ServiceWorkerRegistration: { canOverride: false },
	setInterval: { canOverride: false },
	setTimeout: { canOverride: false },
	TextDecoder: { canOverride: false },
	TextEncoder: { canOverride: false },
	URL: { canOverride: false },
	URLSearchParams: { canOverride: false },
	WebSocket: { canOverride: false },
	Worker: { canOverride: false },
	XMLHttpRequest: { canOverride: false },
};

function getGlobalsForBasicTag(globals) {
	return Object.keys(globals).reduce(
		(tagGlobals, currGlobal) => {
			tagGlobals[currGlobal] = globals[currGlobal].canOverride;
			return tagGlobals;
		}, {});
};

function getGlobalsForESXXXXTag(tag) {
	return Object.keys(esXXXXGlobals).reduce(
		(tagGlobals, currGlobal) => {
			const global = esXXXXGlobals[currGlobal];

			if (global.in.includes(tag)) {
				tagGlobals[currGlobal] = global.canOverride;
			}

			return tagGlobals;
		}, {});
};

const globals = {
	amd: getGlobalsForBasicTag(amdGlobals),
	builtin: getGlobalsForESXXXXTag(BUILTIN),
	browser: getGlobalsForBasicTag(browserGlobals),
	commonjs: getGlobalsForBasicTag(commonjsGlobals),
	es5: getGlobalsForESXXXXTag(ES5),
	es2015: getGlobalsForESXXXXTag(ES2015),
	//es2016: getGlobalsForESXXXXTag(ES2016),
	es2017: getGlobalsForESXXXXTag(ES2017),
	//es2018: getGlobalsForESXXXXTag(ES2018),
	node: getGlobalsForBasicTag(nodeGlobals),
	serviceworker: getGlobalsForBasicTag(serviceworkerGlobals),
	webextensions: getGlobalsForBasicTag(webextensionsGlobals),
	worker: getGlobalsForBasicTag(workerGlobals),
};

module.exports = globals;
