import fs from 'node:fs/promises';

const DATA_FILE = new URL('../globals.json', import.meta.url);

const globals = JSON.parse(await fs.readFile(DATA_FILE));

const getGroupTypeName = (group) => `Globals${group[0].toUpperCase() + group.slice(1).replaceAll('-', '')}`;

const groups = {};
const output = [
	'// This file is autogenerated by scripts/generate-types.mjs',
	'// Do NOT modify this file manually\n'
];

for (const group in globals) {
	const groupType = getGroupTypeName(group);
	groups[group] = groupType;

	output.push(`interface ${getGroupTypeName(group)} {`);

	for (const [rule, status] of Object.entries(globals[group])) {
		output.push(`	readonly '${rule}': ${status};`);
	}

	output.push(`}\n`);
}

output.push(`export default interface globals {`);

for (const [group, groupType] of Object.entries(groups)) {
	output.push(`	readonly '${group}': ${groupType};`);
}

output.push(`}`);

console.log(output.join('\n'));
