name: Update

on:
  workflow_dispatch:
  schedule:
    # “At 00:00 on day-of-month 1.” https://crontab.guru/#0_0_1_*_*
    - cron: "0 0 1 * *"

permissions:
  pull-requests: write
  contents: write

jobs:
  update-on-macos:
    if: github.event_name != 'schedule' || github.repository == 'sindresorhus/globals'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: latest
      - run: npm install
      - run: npm run update
      - uses: actions/upload-artifact@v4
        with:
          name: data
          path: data
          if-no-files-found: error

  update-on-windows:
    if: github.event_name != 'schedule' || github.repository == 'sindresorhus/globals'
    runs-on: windows-latest
    needs: [update-on-macos]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: latest
      - run: npm install
      - uses: actions/download-artifact@v4
        with:
          name: data
          path: data
      - run: npm run update
      - uses: actions/upload-artifact@v4
        with:
          name: data
          path: data
          if-no-files-found: error
          overwrite: true

  update-on-linux:
    if: github.event_name != 'schedule' || github.repository == 'sindresorhus/globals'
    runs-on: ubuntu-latest
    needs: [update-on-windows]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: latest
      - run: npm install
      - uses: actions/download-artifact@v4
        with:
          name: data
          path: data
      # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
      - run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - run: npm run update
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update globals
          branch: automated-update
          branch-suffix: timestamp
          title: Update globals
